// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package localeswitcher.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.IUser;
import com.mendix.webui.CustomJavaAction;

public class SignIn extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __UserAccount;
	private system.proxies.User UserAccount;

	public SignIn(IContext context, IMendixObject UserAccount)
	{
		super(context);
		this.__UserAccount = UserAccount;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.UserAccount = __UserAccount == null ? null : system.proxies.User.initialize(getContext(), __UserAccount);

		// BEGIN USER CODE
		
		IUser user = Core.getUser(getContext(), this.UserAccount.getName());
//		Core.initializeSession(user, this.getContext().getSession().getId().toString());
//		this.getContext().getSession().getLanguage();
//		Core.getComponent().sessionStateStore().
//		if( !user.isAnonymous() )
			ISession s = Core.initializeSession(user, this.getContext().getSession().getId().toString());
//			s.isInteractive();
//		else {
//			Core.logout(this.getContext().getSession());
//			Core.initializeSession(user, null);
//		}
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SignIn";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
