// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package localeswitcher.actions;

import javax.servlet.http.HttpServletResponse;
import com.mendix.core.Core;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.webui.CustomJavaAction;

public class StartLocaleSwitcher extends CustomJavaAction<java.lang.Boolean>
{
	public StartLocaleSwitcher(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		Core.addRequestHandler("locale", new LocaleHandler());
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StartLocaleSwitcher";
	}

	// BEGIN EXTRA CODE
	
	public static class LocaleHandler extends RequestHandler {
		
		
		public LocaleHandler() {
			// TODO Auto-generated constructor stub
		}
		
		
		@Override
		protected void processRequest( IMxRuntimeRequest request, IMxRuntimeResponse response, String args ) throws Exception {
			ISession session = this.getSessionFromRequest(request);

			if( session != null ) {
//				ISession s = Core.initializeGuestSession();
//				s.getUser(Core.createSystemContext());
//				s.getUserName();
//				s.getLanguage();//.getMendixObject().setValue(c, arg1, arg2); 
				Core.initializeSession(session.getUser(Core.createSystemContext()), session.getId().toString());
			}
			
			response.setStatus(HttpServletResponse.SC_SEE_OTHER);
			response.addHeader("location", "../");
		}
		
	}
	
	// END EXTRA CODE
}
