// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package localeswitcher.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import system.proxies.User;

public class UpdateUser extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __currentUserObj;
	private system.proxies.User currentUserObj;

	public UpdateUser(IContext context, IMendixObject currentUserObj)
	{
		super(context);
		this.__currentUserObj = currentUserObj;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.currentUserObj = __currentUserObj == null ? null : system.proxies.User.initialize(getContext(), __currentUserObj);

		// BEGIN USER CODE

		User sessionUser = User.initialize(getContext(), getContext().getSession().getUser(getContext()).getMendixObject() );

		sessionUser.setUser_Language(this.currentUserObj.getUser_Language());
		sessionUser.setUser_TimeZone(this.currentUserObj.getUser_TimeZone());
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UpdateUser";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
